# Generated by Django 4.2 on 2024-02-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verifite_email',
            new_name='is_verified_email',
        ),
    ]
